import Button from '@/Components/Button/Button';
import MentionEditor from '@/Components/Inputs/MentionEditor';
import MentionTextarea from '@/Components/Inputs/MentionTextarea';
import SelectInput from '@/Components/Inputs/SelectInput';
import { Activity, Check, Code, FileCode, Loader2, LockKeyhole, PanelRightOpen, Play, Plus, Send, Settings, ShieldCheck, Trash, Type } from 'lucide-react';
import React, { useEffect, useState, useMemo } from 'react';
import AppSidebar from '@/Components/AppSidebar/AppSidebar';
import "react-quill-new/dist/quill.snow.css";
import { ConfigurationService } from '@/Service/ConfigurationService';
import type { Configuration } from '@/Interface/ConfigurationInterface';
import { toast } from 'react-toastify';
import { useMailQueue } from '@/Context/MailQueueContext';
import { useNavigate } from 'react-router-dom';

const SendMailPage: React.FC = () => {
    const [configs, setConfigs] = useState<Configuration[]>([]);
    const [selectedConfigId, setSelectedConfigId] = useState<string>('');
    const [columns, setColumns] = useState<string[]>(["Email"]);
    const [rows, setRows] = useState<any[][]>([]);
    const [subjectTemplate, setSubjectTemplate] = useState("");
    const [bodyTemplate, setBodyTemplate] = useState("");
    const [loading, setLoading] = useState(true);
    const [currentStep, setCurrentStep] = useState(1);
    const { queue, startQueue } = useMailQueue();
    const navigate = useNavigate();
    const [guideOpen, setGuideOpen] = useState(false);

    useEffect(() => {
        const fetchConfigs = async () => {
            const res = await ConfigurationService.GetConfigs();
            if (res.status) {
                setConfigs(res.data.filter((c: any) => c.status));
            }
            setLoading(false);
        };
        fetchConfigs();
    }, []);

    const configOptions = useMemo(() => {
        return configs.map(c => ({
            label: `${c.mailId} (${c.mailType})`,
            value: (c.id || 0).toString()
        }));
    }, [configs]);

    const replaceVariables = (html: string, row: any[]) => {
        if (!html) return "";
        try {
            const parser = new DOMParser();
            const doc = parser.parseFromString(html, 'text/html');

            // Find all mention spans and replace the entire node with the value
            const mentions = doc.querySelectorAll('span.mention');
            mentions.forEach(mention => {
                const dataId = mention.getAttribute('data-id');
                if (dataId) {
                    const colIndex = columns.indexOf(dataId);
                    if (colIndex !== -1) {
                        const value = row[colIndex] || "";
                        mention.replaceWith(doc.createTextNode(value));
                    }
                }
            });

            let result = doc.body.innerHTML;

            // Replace {{VariableName}} markup generated by MentionTextarea
            columns.forEach((col, index) => {
                if (!col) return;
                const regex = new RegExp(`\\{\\{${col}\\}\\}`, 'g');
                result = result.replace(regex, row[index] || "");
            });

            return result;
        } catch (e) {
            console.error("Variable replacement failed", e);
            return html;
        }
    };

    const stripHtml = (html: string) => {
        const tmp = document.createElement("DIV");
        tmp.innerHTML = html;
        return tmp.textContent || tmp.innerText || "";
    };

    const handleSendMail = () => {
        if (!selectedConfigId) {
            toast.error("Please select a sender account");
            return;
        }
        if (rows.length === 0) {
            toast.error("Please add at least one recipient row");
            return;
        }

        const emailColIndex = columns.findIndex(col => col === "Email");
        if (emailColIndex === -1) {
            toast.error("Recipient 'Email' column is missing");
            return;
        }

        // Build jobs array
        const jobs = rows
            .filter(row => row[emailColIndex])
            .map(row => ({
                configId: parseInt(selectedConfigId),
                recipient: row[emailColIndex],
                subject: stripHtml(replaceVariables(subjectTemplate, row)),
                content: replaceVariables(bodyTemplate, row),
            }));

        if (jobs.length === 0) {
            toast.error("No valid recipients found");
            return;
        }

        // Start the queue and navigate to history
        startQueue(jobs, () => {
            toast.error("Wrong credentials detected! Configuration has been disabled.");
            navigate('/user/configuration');
        });
        toast.info(`Queued ${jobs.length} email(s) for dispatch`);
        navigate('/user/mail-history');
    };

    if (loading) return <div className='flex justify-center items-center h-full'><Loader2 className='animate-spin' /></div>;

    const isStep1Complete = selectedConfigId !== "" && rows.length > 0 && rows[0][columns.indexOf("Email")] !== "";
    const isStep2Complete = isStep1Complete && stripHtml(subjectTemplate).trim() !== "" && stripHtml(bodyTemplate).trim() !== "";

    return (
        <div className='h-full flex flex-col'>
            <div className='min-h-[56px] flex justify-between items-center px-2 md:px-0 mb-4 sm:mb-6'>
                <div className='flex items-center gap-2 sm:gap-3'>
                    <h1 className='text-xl sm:text-2xl md:text-3xl font-black text-slate-800'>Campaign</h1>
                    <div className="p-1.5 sm:p-2 bg-blue-100 rounded-xl text-blue-600">
                        <Send size={18} />
                    </div>
                </div>
                <button
                    onClick={() => setGuideOpen(true)}
                    className="hidden sm:flex items-center gap-2 bg-slate-100 hover:bg-slate-200 px-4 py-2 rounded-xl text-xs font-black uppercase tracking-widest text-slate-500 transition-colors cursor-pointer group"
                >
                    <Activity size={14} className="text-blue-500 group-hover:scale-110 transition-transform" /> 
                    <span>Guided Workflow</span>
                    <PanelRightOpen size={14} className="ml-1 opacity-50" />
                </button>
            </div>

            <AppSidebar
                visible={guideOpen}
                onClose={() => setGuideOpen(false)}
                title="Campaign Guide"
                position="right"
                className="w-[90%] sm:w-[50%] lg:w-[35%]"
            >
                <div className="px-4 py-6 space-y-8">
                    {/* Header Banner */}
                    <div className="p-4 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-2xl border border-blue-100 flex gap-4">
                        <div className="p-2 bg-blue-100 text-blue-600 rounded-xl h-fit">
                            <Activity size={20} />
                        </div>
                        <div>
                            <h3 className="font-bold text-slate-800 text-sm mb-1">How exactly does this work?</h3>
                            <p className="text-xs text-slate-500 leading-relaxed">
                                SMTPConnect allows you to send highly personalized bulk emails using dynamic variables. Follow these steps to set up your first campaign.
                            </p>
                        </div>
                    </div>

                    {/* Step 1 Docs */}
                    <div className="space-y-3">
                        <div className="flex items-center gap-2 mb-2">
                            <span className="w-6 h-6 rounded-md bg-slate-900 text-white flex items-center justify-center text-xs font-black">1</span>
                            <h4 className="text-sm font-black text-slate-800 uppercase tracking-widest">Source & Variables</h4>
                        </div>
                        <div className="pl-8 space-y-4">
                            <div className="flex gap-3 items-start">
                                <Settings size={16} className="text-slate-400 mt-0.5" />
                                <p className="text-xs text-slate-600"><strong className="text-slate-800">Verified Sender:</strong> Choose from the SMTP configurations you previously added in the configurations page.</p>
                            </div>
                            <div className="flex gap-3 items-start">
                                <Type size={16} className="text-slate-400 mt-0.5" />
                                <p className="text-xs text-slate-600"><strong className="text-slate-800">Dynamic Columns:</strong> Add custom columns (e.g., Name, Company, InvoiceUrl) to dynamically replace data in the template. The 'Email' column is mandatory.</p>
                            </div>
                            <div className="flex gap-3 items-start p-3 bg-slate-50 rounded-xl border border-slate-100">
                                <FileCode size={16} className="text-blue-500 mt-0.5" />
                                <div>
                                    <p className="text-xs text-slate-600 mb-1"><strong className="text-slate-800">Adding Recipients:</strong> Add new rows for each recipient. All cells for that row will replace variables for that specific email.</p>
                                    <p className="text-[10px] text-slate-500 italic">Tip: Press 'Add Row' to manually enter contacts.</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Step 2 Docs */}
                    <div className="space-y-3">
                        <div className="flex items-center gap-2 mb-2">
                            <span className="w-6 h-6 rounded-md bg-blue-600 text-white flex items-center justify-center text-xs font-black">2</span>
                            <h4 className="text-sm font-black text-slate-800 uppercase tracking-widest">Template Editing</h4>
                        </div>
                        <div className="pl-8 space-y-4">
                            <div className="flex gap-3 items-start">
                                <Code size={16} className="text-slate-400 mt-0.5" />
                                <p className="text-xs text-slate-600"><strong className="text-slate-800">Using Mentions:</strong> Type <span className="px-1.5 py-0.5 bg-slate-100 rounded text-blue-600 font-mono font-bold">@</span> anywhere in the Subject or Body to open a dropdown of the columns you created in step 1.</p>
                            </div>
                            <p className="text-xs text-slate-600 leading-relaxed bg-slate-50 p-3 rounded-xl border border-slate-100">
                                When the email is sent, the mention (e.g. <strong>@Name</strong>) will be securely replaced with the row value for that specific recipient.
                            </p>
                        </div>
                    </div>

                    {/* Step 3 Docs */}
                    <div className="space-y-3">
                        <div className="flex items-center gap-2 mb-2">
                            <span className="w-6 h-6 rounded-md bg-purple-600 text-white flex items-center justify-center text-xs font-black">3</span>
                            <h4 className="text-sm font-black text-slate-800 uppercase tracking-widest">Dispatch</h4>
                        </div>
                        <div className="pl-8 space-y-4">
                            <div className="flex gap-3 items-start">
                                <Play size={16} className="text-slate-400 mt-0.5" />
                                <p className="text-xs text-slate-600"><strong className="text-slate-800">Start Sequence:</strong> Once launched, the queue manager will take over. It runs in the background to ensure reliable delivery to the SMTP server. You can monitor the progress from the 'History' tab.</p>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </AppSidebar>

            <div className='flex-1 pb-32 lg:pb-20 overflow-auto space-y-12 px-1 md:px-0'>
                {/* Step 1: Source & Recipients */}
                <div className={`transition-all duration-500 ${currentStep === 1 ? 'opacity-100' : 'opacity-40 grayscale-[0.5]'}`}>
                    <div
                        className={`flex items-center gap-3 sm:gap-4 mb-4 sm:mb-6 ${currentStep > 1 ? 'cursor-pointer group/title' : ''}`}
                        onClick={() => currentStep > 1 && setCurrentStep(1)}
                    >
                        <div className={`flex-shrink-0 w-9 h-9 sm:w-12 sm:h-12 rounded-xl sm:rounded-2xl flex items-center justify-center shadow-lg transition-all transform ${currentStep > 1 ? 'bg-gradient-to-br from-green-400 to-emerald-600 shadow-emerald-200 group-hover/title:scale-110' : 'bg-slate-900 shadow-slate-200'}`}>
                            {currentStep > 1 ? <Check size={18} strokeWidth={3} className="text-white" /> : <span className="text-base sm:text-xl font-black text-white">1</span>}
                        </div>
                        <div>
                            <h2 className={`text-sm sm:text-lg font-black transition-colors ${currentStep > 1 ? 'text-slate-400 group-hover/title:text-slate-800' : 'text-slate-800'}`}>Source & Recipients</h2>
                            <p className='text-xs sm:text-sm text-slate-500 font-medium hidden sm:block'>Connect your SMTP and define your audience.</p>
                        </div>
                    </div>

                    <div className={`ml-4 sm:ml-6 border-l-2 border-slate-100 pl-4 sm:pl-10 space-y-8 ${currentStep !== 1 && 'pointer-events-none'}`}>
                        <div className='premium-card p-3 sm:p-6 bg-white/50 border-slate-200/60'>
                            <div className='max-w-md mb-6 sm:mb-8'>
                                <SelectInput
                                    id="senderAccount"
                                    label="Verified Sender Identity"
                                    options={configOptions}
                                    value={selectedConfigId}
                                    onChange={(e) => setSelectedConfigId(e.target.value)}
                                    required
                                />
                            </div>

                            <div className='space-y-4'>
                                <div className='flex flex-col sm:flex-row justify-between items-start sm:items-end gap-3'>
                                    <div>
                                        <h3 className='text-xs sm:text-sm font-black text-slate-800 uppercase tracking-wider'>Data Columns</h3>
                                        <p className='text-[10px] sm:text-xs text-slate-500 font-medium'>Add variables using @Name</p>
                                    </div>
                                    <button
                                        onClick={() => setColumns([...columns, ""])}
                                        className='flex items-center gap-2 px-3 sm:px-4 py-1.5 sm:py-2 bg-slate-900 text-white text-[10px] sm:text-xs font-black uppercase tracking-widest rounded-xl hover:bg-slate-800 transition-all cursor-pointer'
                                    >
                                        <Plus size={12} /> Add Column
                                    </button>
                                </div>
                                <div className='flex flex-wrap gap-2 sm:gap-3 p-3 sm:p-4 bg-slate-50/50 rounded-2xl border border-slate-100'>
                                    {columns.map((col, index) => (
                                        <div key={index} className='px-3 py-2 bg-white rounded-xl flex items-center gap-2 shadow-sm border border-slate-200/60 transition-premium hover:border-blue-400'>
                                            <input
                                                className='bg-transparent border-none outline-none text-xs font-bold text-slate-700 w-20'
                                                value={col}
                                                readOnly={col === "Email"}
                                                onChange={(e) => {
                                                    const newValue = e.target.value;
                                                    const isDuplicate = columns.some(
                                                        (c, i) => i !== index && c.toLowerCase() === newValue.toLowerCase() && newValue.trim() !== ""
                                                    );
                                                    if (isDuplicate) {
                                                        toast.warning(`Column "${newValue}" already exists`);
                                                        return;
                                                    }
                                                    const newColumns = [...columns];
                                                    newColumns[index] = newValue;
                                                    setColumns(newColumns);
                                                }}
                                                placeholder="Name"
                                            />
                                            {col !== "Email" && (
                                                <Trash
                                                    onClick={() => setColumns(columns.filter((_, i) => i !== index))}
                                                    size={14}
                                                    className='cursor-pointer text-slate-300 hover:text-red-500 transition-colors'
                                                />
                                            )}
                                        </div>
                                    ))}
                                </div>
                            </div>

                            <div className='mt-6 sm:mt-10 space-y-4'>
                                <h3 className='text-xs sm:text-sm font-black text-slate-800 uppercase tracking-wider'>Recipient Matrix</h3>
                                <div className="rounded-2xl border border-slate-200 overflow-hidden shadow-sm bg-white">
                                    <div className="overflow-auto max-h-[300px]">
                                        <table className="w-full text-sm border-collapse">
                                            <thead className="bg-slate-50/80 sticky top-0 z-10 backdrop-blur-md">
                                                <tr>
                                                    {columns.map((col, idx) => (
                                                        <th key={idx} className="px-3 sm:px-6 py-3 sm:py-4 text-left text-[9px] sm:text-[10px] font-black uppercase tracking-[0.15em] sm:tracking-[0.2em] text-slate-500 border-b border-slate-200 whitespace-nowrap">{col || "---"}</th>
                                                    ))}
                                                    <th className="px-3 sm:px-6 py-3 sm:py-4 w-12 sm:w-20 text-center border-b border-slate-200"></th>
                                                </tr>
                                            </thead>
                                            <tbody className="divide-y divide-slate-100">
                                                {rows.map((row, rowIndex) => (
                                                    <tr key={rowIndex} className="hover:bg-blue-50/30 transition-colors group">
                                                        {columns.map((_, colIndex) => (
                                                            <td key={colIndex} className="px-2 sm:px-4 py-2 sm:py-3">
                                                                <input
                                                                    className='w-full min-w-[120px] px-2 sm:px-3 py-1.5 sm:py-2 bg-transparent text-xs sm:text-sm text-slate-700 font-medium placeholder:text-slate-300 focus:bg-white rounded-lg transition-all border border-transparent focus:border-blue-200 outline-none'
                                                                    value={row[colIndex] || ""}
                                                                    onChange={(e) => {
                                                                        const newRows = [...rows];
                                                                        newRows[rowIndex][colIndex] = e.target.value;
                                                                        setRows(newRows);
                                                                    }}
                                                                    placeholder={`Value`}
                                                                />
                                                            </td>
                                                        ))}
                                                        <td className="px-4 py-3 text-center">
                                                            <button
                                                                onClick={() => setRows(rows.filter((_, i) => i !== rowIndex))}
                                                                className="p-2 text-slate-300 hover:text-red-500 hover:bg-red-50 rounded-lg transition-all opacity-0 group-hover:opacity-100"
                                                            >
                                                                <Trash size={16} />
                                                            </button>
                                                        </td>
                                                    </tr>
                                                ))}
                                            </tbody>
                                        </table>
                                    </div>
                                    <div className="p-3 sm:p-4 bg-slate-50/50 border-t border-slate-200 flex justify-between items-center">
                                        <span className='text-[10px] sm:text-xs font-bold text-slate-400'>{rows.length} Contacts</span>
                                        <button
                                            onClick={() => setRows([...rows, Array(columns.length).fill("")])}
                                            className="flex items-center gap-1.5 sm:gap-2 px-3 sm:px-4 py-1.5 sm:py-2 text-[10px] sm:text-xs font-black uppercase tracking-widest bg-white border border-slate-200 rounded-xl hover:bg-slate-100 transition-all shadow-sm cursor-pointer"
                                        >
                                            <Plus size={12} /> Add Row
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {currentStep === 1 && (
                            <div className="flex justify-end pt-4">
                                <Button
                                    disabled={!isStep1Complete}
                                    label="Continue to Template"
                                    onClick={() => setCurrentStep(2)}
                                    variant="primary"
                                    className="px-6 sm:px-8 py-2.5 sm:py-3 rounded-xl shadow-lg font-black text-xs sm:text-sm w-full sm:w-auto"
                                />
                            </div>
                        )}
                    </div>
                </div>

                {/* Step 2: Content & Mentions */}
                <div className={`transition-all duration-500 ${currentStep === 2 ? 'opacity-100' : currentStep > 2 ? 'opacity-40 grayscale-[0.5]' : 'opacity-20 pointer-events-none grayscale'}`}>
                    <div
                        className={`flex items-center gap-3 sm:gap-4 mb-4 sm:mb-6 ${currentStep > 2 ? 'cursor-pointer group/title' : ''}`}
                        onClick={() => currentStep > 2 && setCurrentStep(2)}
                    >
                        <div className={`flex-shrink-0 w-9 h-9 sm:w-12 sm:h-12 rounded-xl sm:rounded-2xl flex items-center justify-center shadow-lg transition-all transform ${currentStep > 2 ? 'bg-gradient-to-br from-green-400 to-emerald-600 shadow-emerald-200 group-hover/title:scale-110' : 'bg-blue-600 shadow-blue-200'}`}>
                            {currentStep > 2 ? <Check size={18} strokeWidth={3} className="text-white" /> : <span className="text-base sm:text-xl font-black text-white">2</span>}
                        </div>
                        <div>
                            <div className="flex items-center gap-2 sm:gap-3">
                                <h2 className={`text-sm sm:text-lg font-black transition-colors ${currentStep > 2 ? 'text-slate-400 group-hover/title:text-slate-800' : 'text-slate-800'}`}>Template & Content</h2>
                                {currentStep < 2 && <LockKeyhole size={14} className="text-slate-400" />}
                            </div>
                            <p className='text-xs sm:text-sm text-slate-500 font-medium hidden sm:block'>Compose your message with smart @mentions.</p>
                        </div>
                    </div>

                    <div className={`ml-4 sm:ml-6 border-l-2 border-slate-100 pl-4 sm:pl-10 space-y-4 sm:space-y-6 ${currentStep !== 2 && 'pointer-events-none'}`}>
                        <div className='premium-card p-3 sm:p-6 bg-white/50 border-slate-200/60 space-y-4 sm:space-y-6'>
                            <div>
                                <label className='text-xs font-black uppercase tracking-widest text-slate-400 block mb-2'>Dynamic Subject</label>
                                <MentionTextarea
                                    value={subjectTemplate}
                                    onChange={setSubjectTemplate}
                                    variables={columns}
                                />
                            </div>
                            <div>
                                <label className='text-xs font-black uppercase tracking-widest text-slate-400 block mb-2'>Email Body</label>
                                <MentionEditor
                                    value={bodyTemplate}
                                    onChange={setBodyTemplate}
                                    variables={columns}
                                />
                            </div>
                        </div>

                        <div className="flex flex-col sm:flex-row justify-between items-stretch sm:items-center gap-3 sm:gap-6 pt-4 sm:pt-8">
                            <Button
                                label="Previous Step"
                                onClick={() => setCurrentStep(1)}
                                variant="secondary"
                                className="px-6 sm:px-8 py-2.5 sm:py-3 rounded-xl font-black border-2 border-slate-200 text-xs sm:text-sm w-full sm:w-auto"
                            />
                            <Button
                                disabled={!isStep2Complete}
                                label="Proceed to Review"
                                onClick={() => setCurrentStep(3)}
                                variant="primary"
                                className="px-6 sm:px-8 py-2.5 sm:py-3 rounded-xl shadow-lg font-black text-xs sm:text-sm w-full sm:w-auto"
                            />
                        </div>
                    </div>
                </div>

                {/* Step 3: Review & Dispatch */}
                <div className={`transition-all duration-500 ${currentStep === 3 ? 'opacity-100' : 'opacity-20 pointer-events-none grayscale'}`}>
                    <div className='flex items-center gap-3 sm:gap-4 mb-4 sm:mb-6'>
                        <div className='flex-shrink-0 w-9 h-9 sm:w-12 sm:h-12 rounded-xl sm:rounded-2xl bg-purple-600 text-white flex items-center justify-center shadow-lg shadow-purple-200'>
                            <span className="text-base sm:text-xl font-black">3</span>
                        </div>
                        <div>
                            <div className="flex items-center gap-2 sm:gap-3">
                                <h2 className='text-sm sm:text-lg font-black text-slate-800'>Final Review & Dispatch</h2>
                                {currentStep < 3 && <LockKeyhole size={14} className="text-slate-400" />}
                            </div>
                            <p className='text-xs sm:text-sm text-slate-500 font-medium hidden sm:block'>Preview your final output and start the sequence.</p>
                        </div>
                    </div>

                    <div className={`ml-4 sm:ml-6 border-l-2 border-slate-100 pl-4 sm:pl-10 pb-20 space-y-6 sm:space-y-8 ${currentStep !== 3 && 'pointer-events-none'}`}>
                        <div className='premium-card p-4 sm:p-8 bg-slate-900 text-white overflow-hidden relative min-h-[200px] sm:min-h-[300px]'>
                            <div className="absolute top-0 right-0 p-4 opacity-10">
                                <ShieldCheck size={80} className="sm:w-[120px] sm:h-[120px]" />
                            </div>
                            {rows.length > 0 ? (
                                <div className="relative z-10 space-y-6 sm:space-y-8">
                                    <div>
                                        <span className='text-[9px] sm:text-[10px] font-black uppercase tracking-[0.2em] sm:tracking-[0.3em] text-blue-400 block mb-2 sm:mb-4 truncate'>Preview: {rows[0][columns.indexOf("Email")]}</span>
                                        <div className="text-base sm:text-xl font-bold border-b border-slate-800 pb-3 sm:pb-4" dangerouslySetInnerHTML={{ __html: replaceVariables(subjectTemplate, rows[0]) }}></div>
                                    </div>
                                    <div>
                                        <span className='text-[9px] sm:text-[10px] font-black uppercase tracking-[0.2em] sm:tracking-[0.3em] text-blue-400 block mb-2 sm:mb-4'>Formatted Message</span>
                                        <div 
                                            className="ql-editor p-0 opacity-100 leading-relaxed text-sm sm:text-base text-white/90" 
                                            style={{
                                              fontFamily: 'system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
                                              lineHeight: '1.6'
                                            }}
                                            dangerouslySetInnerHTML={{ __html: replaceVariables(bodyTemplate, rows[0]) }} 
                                        />
                                    </div>
                                </div>
                            ) : null}
                        </div>

                        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 sm:gap-6">
                            <Button
                                label="Previous Step"
                                onClick={() => setCurrentStep(2)}
                                variant="secondary"
                                className="px-6 sm:px-8 py-2.5 sm:py-3 rounded-xl font-black border-2 border-slate-200 w-full sm:w-auto text-xs sm:text-sm"
                            />
                            <Button
                                onClick={handleSendMail}
                                disabled={queue.isActive}
                                label={
                                    <div className="flex items-center gap-2 sm:gap-3">
                                        {queue.isActive ? <Loader2 className='animate-spin' size={18} /> : <Send size={18} />}
                                        <span className="tracking-tight text-xs sm:text-base">
                                            {queue.isActive ? "Dispatching..." : `Launch for ${rows.length} Recipients`}
                                        </span>
                                    </div>
                                }
                                variant='primary'
                                className='h-12 sm:h-16 px-6 sm:px-12 rounded-2xl shadow-2xl shadow-blue-900/30 w-full sm:w-auto'
                            />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default SendMailPage;
